### ISSUE TITLE
Allow application/x-protobuf or application/protobuf for protobuf context type

### ISSUE THREAD

**Issue by allenjohnashton** [RustedBones/akka-http-scalapb#2]
I see that some use application/protobuf as the context type.  However the google libraries use application/x-protobuf (https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/protobuf/ProtocolBuffers#CONTENT_TYPE)

Supporting both headers makes it easier to prevent mismatching headers between client/server.

**Comment by RustedBones** [comment]
Thanks for reporting the issue.

I think the following content-types should be supported by binary protocol:
- `application/protobuf `
- `application/x-protobuf`
- `application/vnd.google.protobuf`
