### ISSUE TITLE
Mixed JSON, protobuf request/response in akka-http-scalapb

### ISSUE THREAD

**Issue by cheatmenot** [RustedBones/akka-http-scalapb#5]
Hello,

I really appreciate this effort to build the library like this. I am currently using this and I really need your help because I have this 3 POST request, all are different and independent from each other, one will be JSON request/response, the other will be protobuf request/response and the other is a combination of JSON request and protobuf response but when I try to extend to ScalaPBSupport all request and response to all the POST request was converted to JSON request/response which does not match my requirement, I am asking if is there a way to target only which request and response will be marshall to JSON? Thank you in advance, if not, is it reasonable to add this feature in this library?

**Comment by RustedBones** [comment]
Hi @cheatmenot. Thanks for reaching out :)

The library serializes the response according to the `Accept` header which is set in the request. If you don't send the header, Json is used by default.

In your case, If you have some control on the requests, you would have to add the `Accept: application/x-protobuf` to the requests that want protobuf responses.

If you don't have the control on the request, you can force the serialization to protobuf by using the `ScalaPBBinarySupport` instead of the `ScalaPBSupport` in your route even if no `Accept` header is sent.

Let me know if this helps.

**Comment by cheatmenot** [comment]
Hey @RustedBones. 

Thank you for your response.
But how about the control over the response, is there a way where I can control it? I have tried it now, yeah you are right on the request, but on the response it is always JSON. Thank you!

**Comment by RustedBones** [comment]
Let's consider this example:

Your api response is defined in a proto file as 
```proto
message Response {
    string stringField  = 1;
    int32 numberFiled   = 2;
}
```

To change serialization in your api for a specific route you can do:
```scala
  val route: Route = path("proto") {
    get {
      import ScalaPBBinarySupport._
      complete(Response("value", 123)) // response serialized as protobuf
    }
  } ~ path("json") {
    get {
      import ScalaPBJsonSupport._
      complete(Response("value", 123)) // response serialized as json      
    }
  }

  Http().bindAndHandle(route, "localhost", 8080)
```

**Comment by cheatmenot** [comment]
Sorry for making you confused.
This is what came out to me from all of this.
My requirement is to have a JSON request and protobuf response and vice versa.
I tried what you sent above and I only get is JSON request/response and protobuf request/response.

So I tried myself, I separate the code of marshaller and unmarshaller for both `ScalaPBJsonSupport` and `ScalaPBBinarySupport` creating a new files `ScalaPBJsonMarshaller`, `ScalaPBJsonUnmarshaller`, `ScalaPBBinaryMarshaller` and `ScalaPBBinaryUnmarshaller`, then I remove my extend ScalaPBSupport and put the marshaller/unmarshaller respectively based on my requirement and it works.

```proto
message Accounts {
  int32 id = 1;
  string name = 2;
}
```
```scala
post {  
  path("accounts") {  
    import ScalaPBBinaryUnmarshaller._
    entity(as[Accounts]) { req =>
      complete{
        import ScalaPBJsonMarshaller._
        req
      }
    }
  }
}
```
```scala
post {  
  path("accounts2") {  
    import ScalaPBJsonUnmarshaller._
    entity(as[Accounts]) { req =>
      complete{
        import ScalaPBBinaryMarshaller._
        req
      }
    }
  }
}
```

**Comment by RustedBones** [comment]
Glad to hear that.
I think it's possible to solve the problem without having to create your own marshaller and unmarshallers. You can import only the desired methods in the right scope:

```scala
post {  
  path("accounts") {  
    import ScalaPBBinarySupport.scalaPBBinaryUnmarshaller
    import ScalaPBJsonSupport.scalaPBJsonMarshaller
    entity(as[Accounts])(complete(_))
  }
}
```
and
```scala
post {  
  path("accounts2") {  
    import ScalaPBJsonSupport.scalaPBJsonUnmarshaller
    import ScalaPBBinarySupport.scalaPBBinaryMarshaller
    entity(as[Accounts])(complete(_))
  }
}
```
Since a solution has been found. I'm closing the issue :)
